# Generated by Django 5.1.1 on 2024-10-30 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Norm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20, verbose_name='название сезона и марка авто')),
                ('liter_per_km', models.FloatField(verbose_name='пробег (л/км)')),
                ('work_with_pump_liter_per_min', models.FloatField(verbose_name='работа с насосом (л/мин)')),
                ('work_without_pump_liter_per_min', models.FloatField(verbose_name='работа без насоса (л/мин)')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='марка автомобиля')),
                ('number', models.CharField(max_length=20, verbose_name='номер автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата начала карты')),
                ('mileage', models.PositiveIntegerField(verbose_name='пробег на 1 число месяца')),
                ('remaining_fuel', models.FloatField(verbose_name='остаток топлива на 1 число месяца')),
                ('norm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.norm')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.truck')),
            ],
        ),
    ]
