# Generated by Django 5.1.1 on 2024-11-05 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departure',
            name='norm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='cards.norm', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departure',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to=settings.AUTH_USER_MODEL, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departure',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='cards.card', verbose_name=''),
        ),
    ]
