# Generated by Django 5.1.1 on 2024-11-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_norm_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='full_name',
            field=models.CharField(default='ggg', max_length=20, verbose_name='полное название автомобиля'),
            preserve_default=False,
        ),
    ]
