# Generated by Django 5.1.1 on 2024-11-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_options_alter_card_norm_alter_card_truck_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departure',
            old_name='dictance',
            new_name='distance',
        ),
    ]
