# Generated by Django 5.1.1 on 2024-11-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_rename_dictance_departure_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departure',
            old_name='probeg_end',
            new_name='mileage_end',
        ),
        migrations.RenameField(
            model_name='departure',
            old_name='probeg_start',
            new_name='mileage_start',
        ),
    ]
