# Generated by Django 5.1.1 on 2024-11-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_departure_fuel_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='remaining_fuel',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='остаток топлива на 1 число месяца'),
        ),
    ]
