# Generated by Django 5.1.1 on 2024-11-03 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_rename_probeg_end_departure_mileage_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='cards.card', verbose_name='карточка'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='date',
            field=models.DateField(verbose_name='дата выезда'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='пройдено (км)'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='mileage_end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='пробег после выезда'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='mileage_start',
            field=models.PositiveIntegerField(verbose_name='пробег перед выездом'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='place_of_work',
            field=models.CharField(max_length=40, verbose_name='место/цель выезда'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='time',
            field=models.TimeField(verbose_name='время выезда'),
        ),
    ]
